version: "3.8"
services:
  pubserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_PROJECT=${GITLAB_PROJECT}
      - TOKENS_FILE=./config/tokens.json
    volumes:
      - .:/app
      - ./config:/app/config
    command: ["/pubserver"]